### ISSUE TITLE
On small devices the main currency converter container is not centered

### ISSUE THREAD

**Issue by Juadebfm** [Mac044/Curr-page#1]
<section  class="container-fluid row m-auto">
        <div class="col-sm-12 col-lg-8">
          
              <h1 class="text-center h3 mt-5">Currency Converter</h1>
      
      1. This is the relevant part of your code,,  you can see that i added  "m-auto" instead of the "mt-5" you added initially. and i added "mt-5" to the h1. Now it will look better on small screens and on all screens
      
     2.  I also added "w-75 py-2 px-2" to your clear button to make it look better
      
      3. On your cards, i also changed the "<div class="card" style="width: 18rem;">" to "<div class="card" style="width: 100%;">" to make it look better
      4. I also added "mb-3" to the first card" "<div class="card mb-3" style="width: 100%;">"
     
     5. For the 2 boxes that contains the 2 select tags "<div class="border col-sm-5 col-md-12 col-lg-5 col-md-5 p-4">", i added "col-md-12" to make them look better

**Comment by Mac044** [comment]
Thank you
